config/routes.rb
# == Route Map
#

Rails.application.routes.draw do
  get "comments/create"
  get "comments/destroy"
  get "posts/index"
  get "posts/show"
  get "posts/new"
  get "posts/create"
  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "posts#index"

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end



end

app/views/shared/_menu.html.erb
<!-- Si NO estamos en las páginas de inicio de sesión o registro, mostramos el navbar -->
<% unless devise_controller? && (controller_name == 'sessions' || controller_name == 'registrations') %>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <%= link_to 'Cat', root_path, class: 'navbar-brand' %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <% if current_page?(posts_path) %>
                          <%= link_to 'Noticias', posts_path, class: 'nav-link nav-link disabled' %>
                        <% else %>
                          <%= link_to 'Noticias', posts_path, class: 'nav-link' %>
                        <% end %>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <% if user_signed_in? %>
                            <%
=begin%>
 <% if current_user.name %>
                                Hola <%= current_user.name %>
                            <% else %> 
<%
=end%>
                                Hola <%= current_user.email %>
                            <%
=begin%>
 <% end %> 
<%
=end%>
                        <% else %>
                            Dale registrate o conectate
                            <% end %>
                        </a>
                        <ul class="dropdown-menu shadow">
                            <% if user_signed_in? %>
                                <li><%= button_to 'Cerrar sesión', destroy_user_session_path, class: 'dropdown-item', method: :delete %></li>
                            <% else %>
                                <li>
                                
                                
                            
                                <%= link_to 'Iniciar sesión',  new_user_session_path, class: 'dropdown-item'%> 


                                
                                
                                </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><%= link_to 'Registro',  new_user_registration_path, class: 'dropdown-item'%></li>
                            <% end %>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>    
<% end %> 